### ISSUE TITLE
Hes not brushing his teethies in the morning

### ISSUE THREAD

**Issue by pfennig42** [wubbl0rz/WidePeepoHappyDesktop#2]
According to dentists it is important to brush your teeth twice a day. But peepo is not doing it in the morning. How can he be a rolemodel then?

**Comment by wubbl0rz** [comment]
fixed. he is not only brushing teeth in the morning but shaving too. XPPeepo_M4x_Morning_ToothbrushShave <img src="https://raw.githubusercontent.com/wubbl0rz/WidePeepoHappyDesktop/master/images/XPPeepo_M4x_Morning_ToothbrushShave.png" width="500px">
